
INSERT INTO "transaction_category" (name, description) VALUES ('Bar, cafe', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Restaurant, fast-food', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Clothes & shoes', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Electronics, accessories', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Free time', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Health and beauty', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Home, garden', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Kids', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Pets, animals', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Energy, utilities', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Maintenance, repairs', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Property insurance', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Rent', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Business trips', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Long distance', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Taxi', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Fuel', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Parking', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Rentals', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Vehicle maintenance', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Active sport, fitness', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Books, audio, subscriptions', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Charity, gifts', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Health care, doctor', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Hobbies', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Life events', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Lottery, gambling', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Wellness, beauty', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Internet', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Postal services', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Software, apps, games', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Charges, Fees', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Child Support', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Loan, interests', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Taxes', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Financial investments', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Realty', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Checks, coupons', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Child Support', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Gifts', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Interests, dividends', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Lottery, gambling', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Refunds (tax, purchase)', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Sale', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Wage, invoices', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Others', '');
INSERT INTO "transaction_category" (name, description) VALUES ('Transfer', '');
